version: "3.8"

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: onlinetest
      POSTGRES_PASSWORD: onlinetest
      POSTGRES_DB: onlinetest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
