# Use the official Python 3.11 image from the Docker Hub
FROM python:3.11-slim

LABEL org.opencontainers.image.source="https://github.com/heigvd-teaching-tools/online-test-platform/database-sandbox-images"

# Install SQLFluff using pip
RUN pip install sqlfluff

# Set the working directory to /app
WORKDIR /app

