# Pull the base image
FROM node:14-bullseye-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
    openssl

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && apt-get install -y docker-ce-cli

# Check if we are in development
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

# Set the working directory
WORKDIR /app

# Install Node.js dependencies
COPY package*.json ./
RUN npm cache clean --force
RUN npm install -g npm@latest
RUN npm install --loglevel verbose

# Copy the app's source code
COPY . .

# Generate Prisma client for multiple platforms
RUN npx prisma generate

# Expose the port
EXPOSE 3000

# Run the app with nodemon for hot reloading
CMD [ "npm", "run", "dev" ]
